live_config_reload = true

[font]
size = 12.0

[font.bold]
family = "JetBrainsMonoNL NFM"
style = "Bold"

[font.normal]
family = "JetBrainsMonoNL NFM"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
chars = "\u001B[1;5D"
key = "Left"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3D"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;5C"
key = "Right"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3C"
key = "Right"
mods = "Alt"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Right"

# [offset]
# x = 0
# y = 0

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "C:\\Windows\\SysWOW64\\WindowsPowerShell\\v1.0\\powershell.exe"
args = ["-noe", "\"&{Import-Module \"\"\"F:\\Program Files\\Microsoft Visual Studio\\Common7\\Tools\\Microsoft.VisualStudio.DevShell.dll\"\"\"; Enter-VsDevShell ba095202 -DevCmdArguments '-arch=x64 -no_logo'}\""]

# [url]
# modifiers = "Control"

# [url.launcher]
# program = "explorer"

[window]
option_as_alt = "Both"
startup_mode = "Maximized"


  #program: C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe
  #args:
  #  - -noe
  #  - -c "&{Import-Module """G:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"""; Enter-VsDevShell 7e993639 -DevCmdArguments '-arch=x64 -no_logo'}"
  #args:
  #  - /k "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat"
  #  - -arch=x64
  #  - -host_arch=x64
